services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dimsymfony\:
    resource: '../src/*'
    exclude: '../src/{Entity,Resources,Tests}'

  Dimsymfony\Controller\Admin\:
    resource: '../src/Controller/Admin'
    tags: ['controller.service_arguments']

  Dimsymfony\Controller\Front\:
    resource: '../src/Controller/Front'
    tags: ['controller.service_arguments']

  Dimsymfony\Service\ItineraryService: # Injection explicite des arguments
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

  doctrine.orm.entity_manager:
    alias: 'Doctrine\ORM\EntityManagerInterface'

  Symfony\Contracts\HttpClient\HttpClientInterface: ~
