# Admin routes
admin_dimsymphony_gestionrdv_index:
  path: /dimsymfony/appointments
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::indexAction'
  methods: [GET]

admin_dimsymphony_gestionrdv_view:
  path: /dimsymfony/appointments/{id}
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::viewAction'
  methods: [GET]
  requirements:
    id: \d+

admin_dimsymphony_gestionrdv_toggle_visited:
  path: /dimsymfony/appointments/{id}/toggle-visited
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::toggleVisitedAction'
  methods: [POST]
  requirements:
    id: \d+

admin_dimsymphony_gestionrdv_delete:
  path: /dimsymfony/appointments/{id}/delete
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::deleteAction'
  methods: [POST]
  requirements:
    id: \d+

admin_dimsymphony_gestionrdv_map:
  path: /dimsymfony/appointments/{id}/map
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::mapAction'
  methods: [GET]
  requirements:
    id: \d+
