dimsymfony_configuration:
  path: /dimsymfony/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\ConfigurationController::indexAction'

dimsymfony_customer_list:
  path: /dimsymfony/customer-list
  methods: [GET]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\CustomerListController::indexAction'

dimsymfony_itinerary:  # Garder cette route, elle est utilisée par AJAX
  path: /dimsymfony/itinerary
  methods: [POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\ItineraryController::generateItineraryAction'

# Route pour le FrontController
dimsymfony_itinerary_form:
  path: /itinerary-form
  methods: [GET, POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Front\ItineraryFormController::indexAction'
