dimsymfony_configuration: # Corrected: Use your module name
  path: /dimsymfony/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\ConfigurationController::indexAction' #Corrected Namespace

dimsymfony_other_page: # Corrected: Use your module name
  path: /dimsymfony/other_page
  methods: [GET, POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\OtherPageController::indexAction' #Corrected Namespace

dimsymfony_api:  # Corrected route name
  path: /dimsymfony/api
  methods: [POST]
  defaults:
    _controller: 'Dimsymfony\Controller\Admin\ApiController::indexAction'
