services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dimsymfony\:
    resource: '../src/*'
    exclude: '../src/{Entity,Resources,Tests}'

  Dimsymfony\Controller\Admin\:
    resource: '../src/Controller/Admin'
    tags: ['controller.service_arguments']

  doctrine.orm.entity_manager:
    alias: 'Doctrine\ORM\EntityManagerInterface'
