
services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $googleApiKey: '%dimsymphony.google_api_key%'

  # Register all controllers in the DimSymfony\Controller namespace
  DimSymfony\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Register all services in the DimSymfony\Service namespace
  DimSymfony\Service\:
    resource: '../src/Service'

  # Specific service for itinerary management
  Dimsymfony.service.itinerary_service:
    class: DimSymfony\Service\ItineraryService
    arguments:
      - '@prestashop.adapter.legacy.context'

  # Register the GestionRdvController (Symfony-based)
  DimSymfony\Controller\Admin\DimSymfonyGestionRdvController:
    class: DimSymfony\Controller\Admin\DimSymfonyGestionRdvController
    arguments:
      - '@Dimsymfony.service.itinerary_service'
      - '%dimsymphony.google_api_key%'
      - '@prestashop.adapter.legacy.context'
    tags:
      - { name: 'controller.service_arguments' }

  # Repository for appointments
  DimSymfony\Repository\AppointmentRepository:
    class: DimSymfony\Repository\AppointmentRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  # Form-related services
  prestashop.module.dimsymfony.form.type.configuration_text:
    class: DimSymfony\Form\ConfigurationFormType
    parent: form.type.translatable.aware
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dimsymfony.form.configuration_text_data_configuration:
    class: DimSymfony\Form\ConfigurationTextDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  prestashop.module.dimsymfony.form.configuration_text_form_data_provider:
    class: DimSymfony\Form\ConfigurationTextFormDataProvider
    arguments:
      - '@prestashop.module.dimsymfony.form.configuration_text_data_configuration'

  prestashop.module.dimsymfony.form.configuration_text_form_data_handler:
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dimsymfony.form.configuration_text_form_data_provider'
      - 'DimSymfony\Form\ConfigurationFormType'
      - 'Configuration'

parameters:
  dimsymphony.google_api_key: '%env(DIMSYMFONY_GOOGLE_API_KEY)%'
